blueprint:
  name: "Open Garage Door for Person"
  description: "Open a garage door when a specific person arrives home."
  domain: automation
  input:
    # ... (inputs remain the same)
  trigger:
    # ... (trigger remains the same)
  condition:
    - condition: state
      entity_id: !input garage_door_entity
      state: closed
    - condition: zone
      entity_id: !input person_entity
      zone: zone.home
    - condition: time
      after: !input time_restriction.start
      before: !input time_restriction.end
    - condition: not
      conditions:
        - condition: state
          entity_id: !input person_entity
          state:
            - home
            - unavailable
            - unknown
          for:
            minutes: !input tolerance
  action:
    - service: cover.open_cover
      target:
        entity_id: !input garage_door_entity
    - delay: '{{ tolerance }}'
    - service: notify.mobile_app_my_phone
      data:
        message: "Garage door opened for {{ trigger.to_state.attributes.friendly_name }}"
