alias: "Garage Doors: Open for Dawn"
description: ""
trigger:
 - platform: state
  entity_id: person.dawn_meudt
  from:
   - not_home
   - Driving
  to: home
condition:
 - condition: not
  conditions:
   - condition: state
    entity_id: person.dawn_meudt
    state: home
    for:
     hours: 0
     minutes: 5
     seconds: 0
 - condition: not
  conditions:
   - condition: state
    entity_id: person.dawn_meudt
    state: unavailable
    for:
     hours: 0
     minutes: 5
     seconds: 0
 - condition: not
  conditions:
   - condition: state
    entity_id: person.dawn_meudt
    state: unknown
    for:
     hours: 0
     minutes: 5
     seconds: 0
 - condition: state
  entity_id: cover.garage_door1
  state: closed
 - condition: zone
  entity_id: person.dawn_meudt
  zone: zone.home
 - condition: time
  after: "06:00:00"
  before: "22:00:00"
action:
 - service: cover.open_cover
  target:
   entity_id: cover.garage_door1
  data: {}
mode: queued
max: 10
