blueprint:
  name: Open Garage Door for Person's Arrival
  description: >-
    **Automatically opens the garage door when a person arrives home, providing convenient and secure access.**
    
    - (ALL tracking entities MUST be defined under the person entity to accurately reflect in this automation.)


    **Key Features:**

    - **Time Restrictions:** Prevents the door from opening during late-night or early-morning hours, enhancing security.
    
    - **Zone Awareness:** Verifies the person is physically within the designated home zone before opening, reducing false triggers.
    
    - **Minimum Away Time:** Avoids accidental activations if the person only leaves briefly, ensuring the door opens only when needed.
    
    - **Recent Opening Prevention:** Avoids opening the door if it has been opened by other means within the last minute.
    
  domain: automation
  input:
    person_entity:
      name: Person
      description: Select the person entity that tracks arrivals home. This entity will trigger the automation.
      selector:
        entity:
          domain: person
    garage_door_entity:
      name: Garage Door
      description: Select the cover entity that controls the garage door. This entity will be opened when the automation triggers.
      selector:
        entity:
          domain: cover
    zone_entity:
      name: Home Zone
      description: Select the zone entity that represents your home area. This zone will confirm when a person has arrived home.
      selector:
        entity:
          domain: zone
    time_restriction_start:
      name: Time Restriction Start
      description: The earliest time of day that the garage door can be automatically opened. This prevents the door from opening during late-night or early-morning hours.
      default: "06:00:00"
    time_restriction_end:
      name: Time Restriction End
      description: The latest time of day that the garage door can be automatically opened. This ensures the door won't open during late-night hours.
      default: "22:00:00"
    not_home_duration:
      name: Required Time Not Home
      description: >-
        The minimum amount of time (in minutes) that a person must have been away from home (not_home, unavailable, or unknown) before the automation triggers. This prevents false triggers if a person only leaves briefly.
      default: 5
trigger:
  - platform: state
    entity_id: !input person_entity
    from:
      - not_home
      - Driving
    to: home
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input person_entity
        state:
          - home
          - unavailable
          - unknown
        for: !input not_home_duration
  - condition: state
    entity_id: !input garage_door_entity
    state: closed
  - condition: zone
    entity_id: !input person_entity
    zone: !input zone_entity
  - condition: time
    after: !input time_restriction_start
    before: !input time_restriction_end
  - condition: template
    value_template: >-
      {{ as_timestamp(now()) - as_timestamp(states.cover.{{ !input garage_door_entity }}.last_changed) > 60 }}
action:
  - service: cover.open_cover
    target:
      entity_id: !input garage_door_entity
mode: queued
max: 10
